
export const categoryOptions = [
  { value: 'accessories', label: 'Accessories' },
  { value: 'gloves', label: 'Gloves' },
  { value: 'harnesses and belts', label: 'Harnesses and belts' },
  { value: 'lashes', label: 'Lashes' },
  { value: 'neckwears', label: 'Neckwears' },
  { value: 'parasols', label: 'Parasols' },
  { value: 'wristcuffs', label: 'Wristcuffs' },
  { value: 'bags', label: 'Bags' },
  { value: 'pins and patches', label: 'Pins and patches' },
  { value: 'shoes', label: 'Shoes' },
  { value: 'purses', label: 'Purses' },
  { value: 'totes', label: 'Totes' },
  { value: 'wallets', label: 'Wallets' },
  { value: 'backpacks', label: 'Backpacks' },
  { value: 'flats', label: 'Flats' },
  { value: 'heels', label: 'Heels' },
  { value: 'platforms', label: 'Platforms' },
  { value: 'brooches', label: 'Brooches' },
  { value: 'buttons', label: 'Buttons' },
  { value: 'enamel pins', label: 'Enamel pins' },
  { value: 'patches', label: 'Patches' },
  { value: 'hair', label: 'Hair' },
  { value: 'bows', label: 'Bows' },
  { value: 'hair claws', label: 'Hair claws' },
  { value: 'scrunchies', label: 'Scrunchies' },
  { value: 'star clips', label: 'Star clips' },
  { value: 'hats', label: 'Hats' },
  { value: 'headbands', label: 'Headbands' },
  { value: 'clothing', label: 'Clothing' },
  { value: 'tops', label: 'Tops' },
  { value: 'dresses', label: 'Dresses' },
  { value: 'bottoms', label: 'Bottoms' },
  { value: 'legwears', label: 'Legwears' },
  { value: 'swimwears', label: 'Swimwears' },
  { value: 'skirts', label: 'Skirts' },
  { value: 'petticoats', label: 'Petticoats' },
  { value: 'bloomers', label: 'Bloomers' },
  { value: 'shorts', label: 'Shorts' },
  { value: 'sweetpants', label: 'Sweetpants' },
  { value: 'blouses', label: 'Blouses' },
  { value: 'button up shirts', label: 'Button up shirts' },
  { value: 't-shirts', label: 'T-shirts' },
  { value: 'sweaters', label: 'Sweaters' },
  { value: 'cardigans', label: 'Cardigans' },
  { value: 'aprons', label: 'Aprons' },
  { value: 'jumperskirts', label: 'Jumperskirts' },
  { value: 'onepieces', label: 'Onepieces' },
  { value: 'leggings', label: 'Leggings' },
  { value: 'tights', label: 'Tights' },
  { value: 'socks', label: 'Socks' },
  { value: 'plus size', label: 'Plus size' },
  { value: 'plus size dresses', label: 'Plus size dresses' },
  { value: 'plus size skirts', label: 'Plus size skirts' },
  { value: 'plus size blouses', label: 'Plus size blouses' },
  { value: 'plus size petticoat & bloomers', label: 'Plus size petticoat & bloomers' },
  { value: 'plus size tops', label: 'Plus size tops' },
  { value: 'jewelry', label: 'Jewelry' },
  { value: 'bracelets', label: 'Bracelets' },
  { value: 'earrings', label: 'Earrings' },
  { value: 'flairs', label: 'Flairs' },
  { value: 'necklaces', label: 'Necklaces' },
  { value: 'rings', label: 'Rings' },
  { value: 'hanging earrings', label: 'Hanging earrings' },
  { value: 'stud earings', label: 'Stud earrings' },
  { value: 'cup on earings', label: 'Cup on earrings' },
  { value: 'rosettes', label: 'Rosettes' },
];
