type BackGroundColor = React.CSSProperties["backgroundColor"];

const colors: { colorName: string; colorCode: BackGroundColor }[] = [
  { colorName: "White", colorCode: "#FFFFFF" },
  { colorName: "Black", colorCode: "#2F2F2F" },
  { colorName: "Wine Red", colorCode: "#B36A6A" },
  { colorName: "Navy", colorCode: "#5D6D7E" },
  { colorName: "Apricot", colorCode: "#FBCEB1" },
  { colorName: "Ivory", colorCode: "#FFFFF0" },
  { colorName: "Pink", colorCode: "#FADADD" },
  { colorName: "Mocha", colorCode: "#C3A38A" },
  { colorName: "Mint Green", colorCode: "#AAF0D1" },
  { colorName: "Sax", colorCode: "#B0D0FF" },
  { colorName: "Red", colorCode: "#F4A6A6" },
  { colorName: "Cream", colorCode: "#FFFDD0" },
  { colorName: "Off White", colorCode: "#FAF9F6" },
  { colorName: "Cheese", colorCode: "#FFFACD" },
  { colorName: "Basil", colorCode: "#C1E1C1" },
  { colorName: "Tomato", colorCode: "#F4A6A6" },
  { colorName: "Cherry Pink", colorCode: "#FFB7C5" },
  { colorName: "Yellow", colorCode: "#FFFACD" },
  { colorName: "Mint", colorCode: "#D0F0C0" },
  { colorName: "Blue", colorCode: "#AED7F4" },
  { colorName: "Purple", colorCode: "#D8BFD8" },
  { colorName: "Violet", colorCode: "#E6E6FA" },
  { colorName: "Dark Violet", colorCode: "#A18FBF" },
  { colorName: "Teal", colorCode: "#B2DFDB" },
  { colorName: "Light Brown", colorCode: "#D2B48C" },
  { colorName: "Peach Pink", colorCode: "#FFDAB9" },
  { colorName: "Dark Red", colorCode: "#B67373" },
  { colorName: "Light Green", colorCode: "#CCFFCC" },
  { colorName: "Light Pink", colorCode: "#FFCCDD" },
  { colorName: "Dark Brown", colorCode: "#8B5C42" },
  { colorName: "Light Purple", colorCode: "#E0BBE4" },
  { colorName: "Beige", colorCode: "#F5F5DC" },
  { colorName: "Taupe", colorCode: "#483C32" },
  { colorName: "Grey", colorCode: "#808080" },
  { colorName: "Rose", colorCode: "#FF007F" },
  { colorName: "Warm Grey", colorCode: "#808A87" },
  { colorName: "Cool Grey", colorCode: "#8C92AC" },
  { colorName: "Brown", colorCode: "#A67B5B" },
  { colorName: "Mauve", colorCode: "#C8A69C" },
  { colorName: "Vintage Rose", colorCode: "#E6C1C6" },
  { colorName: "Aquamarine", colorCode: "#B0E0E6" },
  { colorName: "Light Gray", colorCode: "#D3D3D3" },
  { colorName: "Green", colorCode: "#B5EAD7" },
  { colorName: "Camel", colorCode: "#F2D2BD" },
  { colorName: "White Lace", colorCode: "#F8F8FF" },
  { colorName: "Pink Lace", colorCode: "#FFE4E1" },
  { colorName: "Blue Lace", colorCode: "#DAD0F0" },
  { colorName: "Black Lace", colorCode: "#3B3B3B" },
  { colorName: "Neon", colorCode: "#CCFF00" },
  { colorName: "Pastel", colorCode: "#F0E6FF" },
  { colorName: "Silver", colorCode: "#C0C0C0" },
  { colorName: "Gold", colorCode: "#FFD700" },
  { colorName: "Orange", colorCode: "#FFA07A" },
  { colorName: "Lavender", colorCode: "#E6E6FA" },
  { colorName: "Multicolor", colorCode: "#F8E4FF" },
  { colorName: "Dark Pink", colorCode: "#FF69B4" },
  { colorName: "Hot Pink", colorCode: "#FF1493" },
  { colorName: "Peach", colorCode: "#FFDAB9" },
  { colorName: "Light Blue", colorCode: "#ADD8E6" },
  { colorName: "Wine", colorCode: "#722F37" },
  { colorName: "Gold Orange", colorCode: "#FFC125" },
  { colorName: "Matte Black", colorCode: "#28282B" },
  { colorName: "Gray", colorCode: "#808080" },
  { colorName: "Toffee", colorCode: "#DE6834" },
  { colorName: "Milk Tea", colorCode: "#F2D2BD" },
  { colorName: "Dusty Pink", colorCode: "#D8A2B0" },
  { colorName: "White Pearl", colorCode: "#F0EAD6" },
  { colorName: "Black Pearl", colorCode: "#1E272C" },
  { colorName: "Seafoam Green", colorCode: "#98D9C2" },
  { colorName: "Rainbow", colorCode: "#FFACFC" },
  { colorName: "Dark Chocolate Brown", colorCode: "#4A3728" },
  { colorName: "Chocolate Brown", colorCode: "#7B3F00" },
  { colorName: "Vanilla White", colorCode: "#F3E5AB" },
  { colorName: "Turquoise", colorCode: "#40E0D0" },
  { colorName: "Coffee", colorCode: "#6F4E37" },
  { colorName: "Sun", colorCode: "#FFDD4A" },
  { colorName: "Light Peach", colorCode: "#FFDAB9" },
  { colorName: "Deep Peach", colorCode: "#FFCBA4" },
  { colorName: "Bright Orange", colorCode: "#FF7F50" },
  { colorName: "Lilac", colorCode: "#C8A2C8" },
  { colorName: "Bright Red", colorCode: "#FF5555" },
  { colorName: "Island Pink", colorCode: "#FF9999" },
  { colorName: "Grass", colorCode: "#7CFC00" },
  { colorName: "Sky Blue", colorCode: "#87CEEB" },
  { colorName: "Dusty Blue", colorCode: "#B0C4DE" },
  { colorName: "Royal Blue", colorCode: "#4169E1" },
  { colorName: "Forest Green", colorCode: "#228B22" },
  { colorName: "Deep Orange", colorCode: "#FF4500" },
  { colorName: "Clear", colorCode: "#F0FFFF" },
  { colorName: "Shiny Brown", colorCode: "#8B4513" },
  { colorName: "Red Striped Bows", colorCode: "#FF6666" },
  { colorName: "Yellow Striped Bows", colorCode: "#FFEB99" },
  { colorName: "Yellow Mesh Bows", colorCode: "#FFEE99" },
  { colorName: "Peach Mesh Bows", colorCode: "#FFCBA4" },
  { colorName: "1. White", colorCode: "#FFFFFF" },
  { colorName: "2. Cream", colorCode: "#FFFDD0" },
  { colorName: "3. Coffee", colorCode: "#6F4E37" },
  { colorName: "4. Black", colorCode: "#2F2F2F" },
  { colorName: "5. Sun", colorCode: "#FFDD4A" },
  { colorName: "6. Light Peach", colorCode: "#FFDAB9" },
  { colorName: "7. Deep Peach", colorCode: "#FFCBA4" },
  { colorName: "8. Bright Orange", colorCode: "#FF7F50" },
  { colorName: "9. Light Pink", colorCode: "#FFCCDD" },
  { colorName: "10. Pink", colorCode: "#FADADD" },
  { colorName: "11. Lilac", colorCode: "#C8A2C8" },
  { colorName: "12. Purple", colorCode: "#D8BFD8" },
  { colorName: "13. Bright Red", colorCode: "#FF5555" },
  { colorName: "14. Island Pink", colorCode: "#FF9999" },
  { colorName: "15. Hot Pink", colorCode: "#FF1493" },
  { colorName: "16. Mint", colorCode: "#D0F0C0" },
  { colorName: "17. Grass", colorCode: "#7CFC00" },
  { colorName: "18. Turquoise", colorCode: "#40E0D0" },
  { colorName: "19. Sky Blue", colorCode: "#87CEEB" },
  { colorName: "20. Dusty Blue", colorCode: "#B0C4DE" },
  { colorName: "21. Royal Blue", colorCode: "#4169E1" },
];
export default colors;
