type BackGroundColor = React.CSSProperties["backgroundColor"];

const colors: { colorName: string; colorCode: BackGroundColor }[] = [
  { colorName: "White", colorCode: "#FFFFFF" },
  { colorName: "Black", colorCode: "#2F2F2F" },
  { colorName: "Wine Red", colorCode: "#B36A6A" },
  { colorName: "Navy", colorCode: "#5D6D7E" },
  { colorName: "Apricot", colorCode: "#FBCEB1" },
  { colorName: "Ivory", colorCode: "#FFFFF0" },
  { colorName: "Pink", colorCode: "#FADADD" },
  { colorName: "Mocha", colorCode: "#C3A38A" },
  { colorName: "Mint Green", colorCode: "#AAF0D1" },
  { colorName: "Sax", colorCode: "#B0D0FF" },
  { colorName: "Red", colorCode: "#F4A6A6" },
  { colorName: "Cream", colorCode: "#FFFDD0" },
  { colorName: "Off White", colorCode: "#FAF9F6" },
  { colorName: "Cheese", colorCode: "#FFFACD" },
  { colorName: "Basil", colorCode: "#C1E1C1" },
  { colorName: "Tomato", colorCode: "#F4A6A6" },
  { colorName: "Cherry Pink", colorCode: "#FFB7C5" },
  { colorName: "Yellow", colorCode: "#FFFACD" },
  { colorName: "Mint", colorCode: "#D0F0C0" },
  { colorName: "Blue", colorCode: "#AED7F4" },
  { colorName: "Purple", colorCode: "#D8BFD8" },
  { colorName: "Violet", colorCode: "#E6E6FA" },
  { colorName: "Dak Violet", colorCode: "#A18FBF" },
  { colorName: "Teal", colorCode: "#B2DFDB" },
  { colorName: "Light Brown", colorCode: "#D2B48C" },
  { colorName: "Peach Pink", colorCode: "#FFDAB9" },
  { colorName: "Black x Pink", colorCode: "#2F2F2F" }, // dùng màu đậm pha pastel
  { colorName: "Dark Red", colorCode: "#B67373" },
  { colorName: "Light Green", colorCode: "#CCFFCC" },
  { colorName: "Yellow x Pink", colorCode: "#FFE5B4" },
  { colorName: "Light Pink", colorCode: "#FFCCDD" },
  { colorName: "Dark Brown", colorCode: "#8B5C42" },
  { colorName: "Light Purple", colorCode: "#E0BBE4" },
  { colorName: "Beige", colorCode: "#F5F5DC" },
  { colorName: "Brown/Mauve", colorCode: "#C8A69C" },
  { colorName: "Vintage Rose", colorCode: "#E6C1C6" },
  { colorName: "Aquamarine", colorCode: "#B0E0E6" },
  { colorName: "Light Gray", colorCode: "#D3D3D3" },
  { colorName: "Brown", colorCode: "#A67B5B" },
  { colorName: "Green", colorCode: "#B5EAD7" },
  { colorName: "Camel", colorCode: "#F2D2BD" },
  { colorName: "ivory", colorCode: "#FFFFF0" },
  { colorName: "White w/ Black Bows", colorCode: "#FFFFFF" },
  { colorName: "White w/ White Bows", colorCode: "#FFFFFF" },
  { colorName: "Black w/ Black Bows", colorCode: "#2F2F2F" },
  { colorName: "Pink w/ Black Bows", colorCode: "#FADADD" },
  { colorName: "Pink w/Pink Bows", colorCode: "#FFD1DC" },
  { colorName: "White+White Lace", colorCode: "#F8F8FF" },
  { colorName: "White+Pink Lace", colorCode: "#FFE4E1" },
  { colorName: "Pink+Pink Lace", colorCode: "#FFC0CB" },
  { colorName: "Pink+Blue Lace", colorCode: "#DAD0F0" },
  { colorName: "Black+Black Lace", colorCode: "#3B3B3B" },
  { colorName: "Black+Pink Lace", colorCode: "#2F2F2F" },
  { colorName: "Yellow+Pink Lace", colorCode: "#FFE5B4" },
  { colorName: "Blue+Blue Lace", colorCode: "#D0E8FF" },
  { colorName: "Blue+Pink Lace", colorCode: "#E0CFF2" },
  { colorName: "Black x Brown", colorCode: "#4A3F35" },
  { colorName: "Black x White", colorCode: "#2F2F2F" },
];
export default colors;
