import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import "../lib/fontawesome";
import { ClientProvider } from "@/provider/ClientProvider";

export const metadata: Metadata = {
  title: "Sugar Paws",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
