const API = {
  USERS: "users",
  LOGIN: "auth/signin",
  REGISTER: "auth/signup",
  VERIFY: "auth/verify-code",
  SEND_CODE: "auth/send-code",
  FORGOT_PASSWORD: "auth/forgot-password",
  PRODUCTS: "products/category",
  ALL_PRODUCTS: "products",
  COLORS: "products/colors",
  SIZES: "products/sizes",
  PRODUCT_DETAIL: "products/",
  SEARCH_PRODUCTS: "products/search",
  CART: "cart",
  CART_ITEM: "cart-item",
  ME: "users/me",
  ORDERS: "orders",
  ALL_ORDERS: "orders/all",
  SHIPPING_FEE: "orders/shipping-fee",
  ORDER_CALCULATE_TOTAL: "orders/calculate-total",
  CATEGORIES: "categories",
  PAYMENTS: "payments",
  REVIEWS: "reviews",
  CHAT_MESSAGE: "chat/message",
  CHAT_HISTORY: "chat/history",
  CHAT_CLEAR: "chat/history",
  VOUCHERS: "vouchers",
};

export default API;
