import type { Metadata } from "next";
import React from "react";
import AdminNavbar from "@/components/admin/AdminNavbar";
import AdminProvider from "@/provider/AdminProvider";

export const metadata: Metadata = {
  title: "Sugar Paws",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AdminProvider>
      <main>
        <AdminNavbar />
        {children}
      </main>
    </AdminProvider>
  );
}
