"use client";
import { Product } from "@/types/product";

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Premium Dog Food - Chicken & Rice",
    minPrice: 25.99,
    maxPrice: 45.99,
    displayImage: ["/assets/images/products/dog-food-1.jpg"],
    vendor: "PetNutrition",
    colors: ["brown"],
    totalStock: 150,
    discount: 15,
    rating: 4.8,
    description: "High-quality premium dog food with real chicken and rice",
  },
  {
    id: "2",
    name: "Cat Scratching Post Tower",
    minPrice: 89.99,
    maxPrice: 89.99,
    displayImage: ["/assets/images/products/cat-tower-1.jpg"],
    vendor: "FelineHome",
    colors: ["gray", "beige"],
    totalStock: 45,
    rating: 4.6,
    description:
      "Multi-level cat tower with scratching posts and cozy hideouts",
  },
  {
    id: "3",
    name: "Interactive Dog Toy Ball",
    minPrice: 12.99,
    maxPrice: 18.99,
    displayImage: ["/assets/images/products/dog-toy-1.jpg"],
    vendor: "PlayfulPaws",
    colors: ["red", "blue", "green"],
    totalStock: 200,
    discount: 10,
    rating: 4.5,
    description:
      "Durable interactive ball that keeps dogs entertained for hours",
  },
  {
    id: "4",
    name: "Orthopedic Pet Bed - Large",
    minPrice: 75.99,
    maxPrice: 125.99,
    displayImage: ["/assets/images/products/pet-bed-1.jpg"],
    vendor: "ComfortPet",
    colors: ["brown", "gray", "navy"],
    totalStock: 80,
    rating: 4.9,
    description: "Memory foam orthopedic bed for senior pets and large breeds",
  },
  {
    id: "5",
    name: "Automatic Pet Water Fountain",
    minPrice: 35.99,
    maxPrice: 55.99,
    displayImage: ["/assets/images/products/water-fountain-1.jpg"],
    vendor: "HydratePet",
    colors: ["white", "gray"],
    totalStock: 120,
    discount: 20,
    rating: 4.7,
    description: "Circulating water fountain with filtration system",
  },
];
