import CategoryBannerClient from "@/components/category/CategoryBannerClient";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Sugar Paws",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <CategoryBannerClient />
      {children}
    </div>
  );
}
